### ISSUE TITLE
NutritionScreen inconsistently emitting name update

### ISSUE THREAD

**Issue by medwardson** [swent-group10/polyfit#182]
I've noticed an issue when you have ingredients, nutritional info, and a name, but you can not proceed to save your meal. I spent some time looking at it and haven't figured out why it is not emitting the name properly, but it seems like when the name is getting updated, the state doesn't always rerun.

![Image](https://github.com/swent-group10/polyfit/assets/68757340/10f37a87-7eb4-420e-8f31-3119bd84246c)

**Comment by RandomUsername1315** [comment]
Possible issue found : the listener of meal that is used to know if a given mean is complete or not is lauched using the viewmodelscope -> when changed to gloabal, it seems to resolve the issue
