### ISSUE TITLE
Set up APK Pipeline

### ISSUE THREAD

**Issue by medwardson** [swent-group10/polyfit#65]

**Comment by RandomUsername1315** [comment]
- This PR was reopened due to an issue with API keys. Look at #83 for more detail.

**Comment by CharlyCst** [comment]
Hi all, I tried installing the APK from my phone by downloading from this workflow run: https://github.com/swent-group10/polyfit/actions/runs/8647361276
If I am not mistaken, this workflow should include the latest PR. Yet I can't install it on my phone as I get the following error when running `adb install app-release-unsigned.apk` where `app-release-unsigned.apk` is the APK downloaded from the workflow:

```
Performing Streamed Install
adb: failed to install app-release-unsigned.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting cer
tificates for /data/app/vmdl1357602194.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1357602194.tmp
/base.apk: Attempt to get length of null array]
```

It looks suspicious that the APK has "unsigned" in its name, am I doing everything right?
